### ISSUE TITLE
Using with zgen get compdef command not found

### ISSUE THREAD

**Issue by alextes** [prezto-contributions/prezto-kubectl#1]
### Description

After zgen init has run, subsequent runs result in a "compdef command not found" error originating from the `source <(kubectl completion zsh)` line in init.zsh . It's 'fixed' by putting a `autoload -U +X compinit && compinit` before it.

### Expected behavior

I'm not sure how this should work exactly but I'm guessing zgen wants to somehow run completion generating code during its special one-time init, which it does once to enable faster subsequent loads. So it's a guess, but expected behavior would be to run completion only during zgen's init phase and not on subsequent loads. Perhaps though it is simply to run `autoload -U +X compinit && compinit` before sourcing the completions. I'm not sure.

### Actual behavior

Error on every zsh start.

### Steps to Reproduce

Not sure. For me it happens with zsh, zgen, kubectl, and this plugin but then I have a bunch of other things going on.

### Versions

  - Prezto commit: 3888227
  - ZSH version: 5.8
  - OS information: macOS

**Comment by alextes** [comment]
Perhaps it's too vague to fix this but then at least this might hit some people's google searches. I reinstalled my OS and after cloning my dotfiles it took me a while to get rid of this error again.

Thanks for the great plugin 🙏 !

**Comment by tarak** [comment]
The [StackOverflow qestion](https://stackoverflow.com/a/60383091) links to the [oh-my-zsh kubectl plugin](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/kubectl/kubectl.plugin.zsh) where the completion is written to a file:

```
if (( $+commands[kubectl] )); then
    __KUBECTL_COMPLETION_FILE="${ZSH_CACHE_DIR}/kubectl_completion"

    if [[ ! -f $__KUBECTL_COMPLETION_FILE ]]; then
        kubectl completion zsh >! $__KUBECTL_COMPLETION_FILE
    fi

    [[ -f $__KUBECTL_COMPLETION_FILE ]] && source $__KUBECTL_COMPLETION_FILE

    unset __KUBECTL_COMPLETION_FILE
fi
```

Could you test if this solves your issue? I will implement this anyway, looks better to me...

**Comment by tarak** [comment]
By the way, @alextes, i didn't even know if someone is using this, so thank you for letting me know.

**Comment by tarak** [comment]
After some research I found this:

https://medium.com/@jzelinskie/please-dont-ship-binaries-with-shell-completion-as-commands-a8b1bcb8a0d0

This article suggests to remove the [line](https://github.com/prezto-contributions/prezto-kubectl/blob/master/init.zsh#L5) altogether: `source <(kubectl completion zsh)`

I prefer this solution, as I see that you are on macOS, probably using Brew to install `kubectl`, which ships autocompletion, see
`/usr/local/share/zsh/site-functions/_kubectl`

**Comment by alextes** [comment]
@tarak yup, appears to work great without that line. `_kubectl` is indeed present. I'm guessing faster shell start as a bonus 🙌 .
